/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'filled' : IDL.Null,
});
export const OrderSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
export const OrderType = IDL.Variant({
  'limit' : IDL.Null,
  'market' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'assetId' : IDL.Nat,
  'side' : OrderSide,
  'orderType' : OrderType,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Float64,
  'price' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Holding = IDL.Record({
  'currentPrice' : IDL.Float64,
  'assetId' : IDL.Nat,
  'name' : IDL.Text,
  'averageCost' : IDL.Float64,
  'quantity' : IDL.Float64,
  'symbol' : IDL.Text,
});
export const Portfolio = IDL.Record({
  'dailyPnLPercent' : IDL.Float64,
  'totalValue' : IDL.Float64,
  'holdings' : IDL.Vec(Holding),
  'dailyPnL' : IDL.Float64,
});
export const Asset = IDL.Record({
  'id' : IDL.Nat,
  'currentPrice' : IDL.Float64,
  'change24h' : IDL.Float64,
  'name' : IDL.Text,
  'changePercent24h' : IDL.Float64,
  'symbol' : IDL.Text,
});

export const idlService = IDL.Service({
  'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
  'getSamplePriceHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(IDL.Float64)],
      ['query'],
    ),
  'getWatchlist' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        OrderSide,
        OrderType,
        IDL.Float64,
        IDL.Float64,
      ],
      [IDL.Nat],
      [],
    ),
  'searchAssets' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'filled' : IDL.Null,
  });
  const OrderSide = IDL.Variant({ 'buy' : IDL.Null, 'sell' : IDL.Null });
  const OrderType = IDL.Variant({ 'limit' : IDL.Null, 'market' : IDL.Null });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'assetId' : IDL.Nat,
    'side' : OrderSide,
    'orderType' : OrderType,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Float64,
    'price' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Holding = IDL.Record({
    'currentPrice' : IDL.Float64,
    'assetId' : IDL.Nat,
    'name' : IDL.Text,
    'averageCost' : IDL.Float64,
    'quantity' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  const Portfolio = IDL.Record({
    'dailyPnLPercent' : IDL.Float64,
    'totalValue' : IDL.Float64,
    'holdings' : IDL.Vec(Holding),
    'dailyPnL' : IDL.Float64,
  });
  const Asset = IDL.Record({
    'id' : IDL.Nat,
    'currentPrice' : IDL.Float64,
    'change24h' : IDL.Float64,
    'name' : IDL.Text,
    'changePercent24h' : IDL.Float64,
    'symbol' : IDL.Text,
  });
  
  return IDL.Service({
    'cancelOrder' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPortfolio' : IDL.Func([], [Portfolio], ['query']),
    'getSamplePriceHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(IDL.Float64)],
        ['query'],
      ),
    'getWatchlist' : IDL.Func([], [IDL.Vec(Asset)], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          OrderSide,
          OrderType,
          IDL.Float64,
          IDL.Float64,
        ],
        [IDL.Nat],
        [],
      ),
    'searchAssets' : IDL.Func([IDL.Text], [IDL.Vec(Asset)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };