/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Asset {
  'id' : bigint,
  'currentPrice' : number,
  'change24h' : number,
  'name' : string,
  'changePercent24h' : number,
  'symbol' : string,
}
export interface Holding {
  'currentPrice' : number,
  'assetId' : bigint,
  'name' : string,
  'averageCost' : number,
  'quantity' : number,
  'symbol' : string,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'assetId' : bigint,
  'side' : OrderSide,
  'orderType' : OrderType,
  'timestamp' : bigint,
  'quantity' : number,
  'price' : number,
  'symbol' : string,
}
export type OrderSide = { 'buy' : null } |
  { 'sell' : null };
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'filled' : null };
export type OrderType = { 'limit' : null } |
  { 'market' : null };
export interface Portfolio {
  'dailyPnLPercent' : number,
  'totalValue' : number,
  'holdings' : Array<Holding>,
  'dailyPnL' : number,
}
export interface _SERVICE {
  'cancelOrder' : ActorMethod<[bigint], boolean>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPortfolio' : ActorMethod<[], Portfolio>,
  'getSamplePriceHistory' : ActorMethod<[bigint], Array<number>>,
  'getWatchlist' : ActorMethod<[], Array<Asset>>,
  'placeOrder' : ActorMethod<
    [bigint, string, string, OrderSide, OrderType, number, number],
    bigint
  >,
  'searchAssets' : ActorMethod<[string], Array<Asset>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];