/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Holding {
    currentPrice: number;
    assetId: bigint;
    name: string;
    averageCost: number;
    quantity: number;
    symbol: string;
}
export interface Asset {
    id: bigint;
    currentPrice: number;
    change24h: number;
    name: string;
    changePercent24h: number;
    symbol: string;
}
export interface Portfolio {
    dailyPnLPercent: number;
    totalValue: number;
    holdings: Array<Holding>;
    dailyPnL: number;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    assetId: bigint;
    side: OrderSide;
    orderType: OrderType;
    timestamp: bigint;
    quantity: number;
    price: number;
    symbol: string;
}
export enum OrderSide {
    buy = "buy",
    sell = "sell"
}
export enum OrderStatus {
    cancelled = "cancelled",
    pending = "pending",
    filled = "filled"
}
export enum OrderType {
    limit = "limit",
    market = "market"
}
export interface backendInterface {
    cancelOrder(orderId: bigint): Promise<boolean>;
    getOrders(): Promise<Array<Order>>;
    getPortfolio(): Promise<Portfolio>;
    getSamplePriceHistory(assetId: bigint): Promise<Array<number>>;
    getWatchlist(): Promise<Array<Asset>>;
    placeOrder(assetId: bigint, symbol: string, name: string, side: OrderSide, orderType: OrderType, quantity: number, price: number): Promise<bigint>;
    searchAssets(filterText: string): Promise<Array<Asset>>;
}
import type { Order as _Order, OrderSide as _OrderSide, OrderStatus as _OrderStatus, OrderType as _OrderType } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelOrder(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelOrder(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelOrder(arg0);
            return result;
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPortfolio(): Promise<Portfolio> {
        if (this.processError) {
            try {
                const result = await this.actor.getPortfolio();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPortfolio();
            return result;
        }
    }
    async getSamplePriceHistory(arg0: bigint): Promise<Array<number>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSamplePriceHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSamplePriceHistory(arg0);
            return result;
        }
    }
    async getWatchlist(): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWatchlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWatchlist();
            return result;
        }
    }
    async placeOrder(arg0: bigint, arg1: string, arg2: string, arg3: OrderSide, arg4: OrderType, arg5: number, arg6: number): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2, to_candid_OrderSide_n10(this._uploadFile, this._downloadFile, arg3), to_candid_OrderType_n12(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2, to_candid_OrderSide_n10(this._uploadFile, this._downloadFile, arg3), to_candid_OrderType_n12(this._uploadFile, this._downloadFile, arg4), arg5, arg6);
            return result;
        }
    }
    async searchAssets(arg0: string): Promise<Array<Asset>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAssets(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAssets(arg0);
            return result;
        }
    }
}
function from_candid_OrderSide_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderSide): OrderSide {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_OrderType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderType): OrderType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    assetId: bigint;
    side: _OrderSide;
    orderType: _OrderType;
    timestamp: bigint;
    quantity: number;
    price: number;
    symbol: string;
}): {
    id: bigint;
    status: OrderStatus;
    assetId: bigint;
    side: OrderSide;
    orderType: OrderType;
    timestamp: bigint;
    quantity: number;
    price: number;
    symbol: string;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n4(_uploadFile, _downloadFile, value.status),
        assetId: value.assetId,
        side: from_candid_OrderSide_n6(_uploadFile, _downloadFile, value.side),
        orderType: from_candid_OrderType_n8(_uploadFile, _downloadFile, value.orderType),
        timestamp: value.timestamp,
        quantity: value.quantity,
        price: value.price,
        symbol: value.symbol
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    filled: null;
}): OrderStatus {
    return "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "filled" in value ? OrderStatus.filled : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    buy: null;
} | {
    sell: null;
}): OrderSide {
    return "buy" in value ? OrderSide.buy : "sell" in value ? OrderSide.sell : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    limit: null;
} | {
    market: null;
}): OrderType {
    return "limit" in value ? OrderType.limit : "market" in value ? OrderType.market : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n2(_uploadFile, _downloadFile, x));
}
function to_candid_OrderSide_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderSide): _OrderSide {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_OrderType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): _OrderType {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderSide): {
    buy: null;
} | {
    sell: null;
} {
    return value == OrderSide.buy ? {
        buy: null
    } : value == OrderSide.sell ? {
        sell: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderType): {
    limit: null;
} | {
    market: null;
} {
    return value == OrderType.limit ? {
        limit: null
    } : value == OrderType.market ? {
        market: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
